select * from Products
select * from Customer
select * from Addresses
select * from Customer_Addresses
select * from Customer_Orders
select * from Customer_Orders_Products
select * from Customer_Orders_Dilivery
select * from Reference_Address_Types
select * from Suppliers
